/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.panel.perjalanan;

import app.table.Bank;
import app.table.KeuanganMobil;
import app.table.Mobil;
import app.table.Pemasukan;
import app.table.Pengeluaran;
import app.table.Perjalanan;
import app.table.PerjalananPemasukan;
import app.table.PerjalananPengeluaran;
import app.table.Saldo;
import app.table.Trips;
import app.table.Util;
import static app.utils.ExcelConverter.ExcelConverter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import app.view.ShowRoom;
import app.view.utilsPanel;
import com.joobar.csvbless.CSVUtil;
import com.joobar.csvbless.WriteStep;
import com.toedter.calendar.JDateChooserCellEditor;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.EventQueue;
import java.beans.Beans;
import java.io.File;
import java.math.BigInteger;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import javaslang.Tuple;
import javax.persistence.RollbackException;
import javax.persistence.TypedQuery;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author SEED
 */
public class panelPerjalanan extends JPanel {
    Bank Peter;
    public panelPerjalanan() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
       for (int i = 0; i < this.detailTable.getColumnCount(); i++) {
                this.detailTable.getColumnModel().getColumn(i).setPreferredWidth(220);
        }
    }

    public List<Bank> getBankList() {
        return bankList;
    }

    public void setBankList(List<Bank> bankList) {
        this.bankList = bankList;
    }
    
    public void Refresh()
    {
            this.refreshButtonActionPerformed(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("blessingPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Trips t");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        jDialog1 = new javax.swing.JDialog();
        inputPanel1 = new app.utils.inputPanel(app.table.Trips.class);
        newButton = new javax.swing.JButton();
        bankQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM Bank b order by b.namaBank");
        bankList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : bankQuery.getResultList();
        newDetailButton = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        inputPanel2 = new app.utils.inputPanel(app.table.PerjalananPemasukan.class);
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        newButton2 = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        inputPanel3 = new app.utils.inputPanel(app.table.PerjalananKembalikan.class);
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        newButton3 = new javax.swing.JButton();
        jDialog4 = new javax.swing.JDialog();
        inputPanel4 = new app.utils.inputPanel(app.table.PerjalananPengeluaran.class);
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        newButton4 = new javax.swing.JButton();
        jDialog5 = new javax.swing.JDialog();
        inputPanel5 = new app.utils.inputPanel(app.table.MobilPengeluaran.class);
        jLabel5 = new javax.swing.JLabel();
        newButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        newButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        mobilQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Mobil m");
        mobilList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(mobilQuery.getResultList());
        newDetailButton4 = new javax.swing.JButton();
        GantiDialog6 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        newButton1 = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        refreshButton1 = new javax.swing.JButton();
        saveButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        newDetailButton1 = new javax.swing.JButton();
        newDetailButton2 = new javax.swing.JButton();
        newDetailButton3 = new javax.swing.JButton();
        deleteDetailButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        gantiLaporanButton = new javax.swing.JButton();
        detailScrollPane = new javax.swing.JScrollPane();
        detailTable = new javax.swing.JTable();

        FormListener formListener = new FormListener();

        jDialog1.setTitle("Data Laporan Perjalanan");
        jDialog1.setModal(true);

        inputPanel1.setLayout(new java.awt.GridLayout(0, 2));
        jDialog1.getContentPane().add(inputPanel1, java.awt.BorderLayout.CENTER);

        newButton.setText("Simpan");
        newButton.addActionListener(formListener);
        jDialog1.getContentPane().add(newButton, java.awt.BorderLayout.PAGE_START);

        newDetailButton.setText("New");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), newDetailButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newDetailButton.addActionListener(formListener);

        jDialog2.setTitle("Input data Transfer Uang");
        jDialog2.setModal(true);

        jLabel1.setText("Bank");
        inputPanel2.add(jLabel1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setSelectedIndex(-1);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${bankList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jComboBox2);
        bindingGroup.addBinding(jComboBoxBinding);

        jComboBox2.addActionListener(formListener);
        inputPanel2.add(jComboBox2);

        jTextField2.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.info}"), jTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        inputPanel2.add(jTextField2);

        newButton2.setText("Simpan");
        newButton2.addActionListener(formListener);
        inputPanel2.add(newButton2);

        jDialog2.getContentPane().add(inputPanel2, java.awt.BorderLayout.CENTER);

        jDialog3.setTitle("Input Data Kembalikan");
        jDialog3.setModal(true);

        jLabel2.setText("Bank");
        inputPanel3.add(jLabel2);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setSelectedIndex(-1);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${bankList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jComboBox3);
        bindingGroup.addBinding(jComboBoxBinding);

        inputPanel3.add(jComboBox3);

        jTextField3.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.info}"), jTextField3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        inputPanel3.add(jTextField3);

        newButton3.setText("Simpan");
        newButton3.addActionListener(formListener);
        inputPanel3.add(newButton3);

        jDialog3.getContentPane().add(inputPanel3, java.awt.BorderLayout.CENTER);

        jDialog4.setTitle("Input Data Pakai");
        jDialog4.setModal(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${peter.foo}"), jLabel3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        inputPanel4.add(jLabel3);

        jTextField4.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.info}"), jTextField4, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        inputPanel4.add(jTextField4);

        newButton4.setText("Simpan");
        newButton4.addActionListener(formListener);
        inputPanel4.add(newButton4);

        jDialog4.getContentPane().add(inputPanel4, java.awt.BorderLayout.CENTER);

        jDialog5.setTitle("Input Data Pakai");
        jDialog5.setModal(true);

        jLabel5.setText("Mobil");
        inputPanel5.add(jLabel5);

        newButton6.setText("Cari");
        newButton6.addActionListener(formListener);
        inputPanel5.add(newButton6);

        jTextField1.setLayout(new BorderLayout());
        jTextField1.add(newButton6, BorderLayout.LINE_END);
        inputPanel5.add(jTextField1);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mobilList, jComboBox5);
        bindingGroup.addBinding(jComboBoxBinding);

        inputPanel5.add(jComboBox5);

        jTextField5.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.info}"), jTextField5, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        inputPanel5.add(jTextField5);

        newButton5.setText("Simpan");
        newButton5.addActionListener(formListener);
        inputPanel5.add(newButton5);

        jDialog5.getContentPane().add(inputPanel5, java.awt.BorderLayout.CENTER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${bankList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jComboBox1);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.transfer.transaksi.bankId}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${bankList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jComboBox4);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.kembali.transaksi.bankId}"), jComboBox4, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        newDetailButton4.setText("Pengeluaran Belanja Mobil");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), newDetailButton4, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newDetailButton4.addActionListener(formListener);

        GantiDialog6.getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        jLabel4.setText("GANTI LAPORAN PERJALANAN KE");
        GantiDialog6.getContentPane().add(jLabel4);

        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, jComboBox6);
        bindingGroup.addBinding(jComboBoxBinding);

        GantiDialog6.getContentPane().add(jComboBox6);

        jButton2.setText("SIMPAN");
        jButton2.addActionListener(formListener);
        GantiDialog6.getContentPane().add(jButton2);

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        newButton1.setText("Tambah");
        newButton1.addActionListener(formListener);
        jPanel1.add(newButton1);

        deleteButton.setText("Hapus");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);
        jPanel1.add(deleteButton);

        refreshButton1.setText("Refresh");
        refreshButton1.addActionListener(formListener);
        jPanel1.add(refreshButton1);

        saveButton1.setText("Simpan");
        saveButton1.addActionListener(formListener);
        jPanel1.add(saveButton1);

        jButton1.setText("Print");
        jButton1.addActionListener(formListener);
        jPanel1.add(jButton1);

        add(jPanel1);

        masterTable.setAutoCreateRowSorter(true);
        masterTable.setRowHeight(30);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tripsId}"));
        columnBinding.setColumnName("Trips Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${keterangan}"));
        columnBinding.setColumnName("Keterangan");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${perjalananke}"));
        columnBinding.setColumnName("Perjalananke");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tanggalBerangkat}"));
        columnBinding.setColumnName("Tanggal Berangkat");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tanggalKembali}"));
        columnBinding.setColumnName("Tanggal Kembali");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalKirim}"));
        columnBinding.setColumnName("Total Kirim");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalPakai}"));
        columnBinding.setColumnName("Total Pakai");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalKembali}"));
        columnBinding.setColumnName("Total Kembali");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${totalSaldo}"));
        columnBinding.setColumnName("Saldo Sisa");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(masterTable);

        add(masterScrollPane);

        newDetailButton1.setText("Transfer");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), newDetailButton1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newDetailButton1.addActionListener(formListener);
        jPanel2.add(newDetailButton1);

        newDetailButton2.setText("Kembalikan");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), newDetailButton2, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newDetailButton2.addActionListener(formListener);
        jPanel2.add(newDetailButton2);

        newDetailButton3.setText("Pengeluaran Perjalanan");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), newDetailButton3, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newDetailButton3.addActionListener(formListener);
        jPanel2.add(newDetailButton3);

        deleteDetailButton.setText("Hapus");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteDetailButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteDetailButton.addActionListener(formListener);
        jPanel2.add(deleteDetailButton);

        saveButton.setText("Simpan");
        saveButton.addActionListener(formListener);
        jPanel2.add(saveButton);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(formListener);
        jPanel2.add(refreshButton);

        gantiLaporanButton.setText("Ganti Laporan Perjalanan");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, detailTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), gantiLaporanButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        gantiLaporanButton.addActionListener(formListener);
        jPanel2.add(gantiLaporanButton);

        add(jPanel2);

        detailTable.setDefaultEditor(String.class, new app.utils.TablePopupEditor());
        detailTable.setDefaultEditor(java.math.BigInteger.class, new app.utils.TablePopupEditor());
        detailTable.setDefaultEditor(Date.class, new JDateChooserCellEditor());
        detailTable.setDefaultRenderer(java.math.BigInteger.class, new app.utils.NominalRender());
        masterTable.setDefaultEditor(String.class, new app.utils.TablePopupEditor());
        masterTable.setDefaultEditor(Date.class, new JDateChooserCellEditor());
        masterTable.setDefaultEditor(java.math.BigInteger.class, new app.utils.TablePopupEditor());
        masterTable.setDefaultRenderer(java.math.BigInteger.class, new app.utils.NominalRender());
        detailTable.setAutoCreateRowSorter(true);
        detailTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        detailTable.setRowHeight(30);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${selectedElement.perjalananList}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, eLProperty, detailTable);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("REF");
        columnBinding.setColumnClass(Long.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${keterangan}"));
        columnBinding.setColumnName("Keterangan");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tanggal2}"));
        columnBinding.setColumnName("Tanggal");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${kirim2}"));
        columnBinding.setColumnName("Transfer");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${kembali2}"));
        columnBinding.setColumnName("Kembalikan");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pengeluaran}"));
        columnBinding.setColumnName("Pengeluaran Perjalanan");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${saldo}"));
        columnBinding.setColumnName("Saldo");
        columnBinding.setColumnClass(java.math.BigInteger.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tripsTripsId.perjalananke}"));
        columnBinding.setColumnName("Perjalanan KE");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${transfer.transaksi.bankId}"));
        columnBinding.setColumnName("Transfer Dari");
        columnBinding.setColumnClass(app.table.Bank.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${kembali.transaksi.bankId}"));
        columnBinding.setColumnName("Kembalikan Ke");
        columnBinding.setColumnClass(app.table.Bank.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${transaksi.bankId}"));
        columnBinding.setColumnName("Diterima/Dikirim");
        columnBinding.setColumnClass(app.table.Bank.class);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        detailScrollPane.setViewportView(detailTable);
        if (detailTable.getColumnModel().getColumnCount() > 0) {
            detailTable.getColumnModel().getColumn(8).setCellEditor(new javax.swing.DefaultCellEditor(jComboBox1));
            detailTable.getColumnModel().getColumn(9).setCellEditor(new javax.swing.DefaultCellEditor(jComboBox4));
        }

        add(detailScrollPane);

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == newButton1) {
                panelPerjalanan.this.newButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                panelPerjalanan.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton1) {
                panelPerjalanan.this.refreshButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton1) {
                panelPerjalanan.this.saveButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                panelPerjalanan.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == newDetailButton1) {
                panelPerjalanan.this.newDetailButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == newDetailButton2) {
                panelPerjalanan.this.newDetailButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == newDetailButton4) {
                panelPerjalanan.this.newDetailButton4ActionPerformed(evt);
            }
            else if (evt.getSource() == newDetailButton3) {
                panelPerjalanan.this.newDetailButton3ActionPerformed(evt);
            }
            else if (evt.getSource() == deleteDetailButton) {
                panelPerjalanan.this.deleteDetailButtonActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                panelPerjalanan.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                panelPerjalanan.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                panelPerjalanan.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newDetailButton) {
                panelPerjalanan.this.newDetailButtonActionPerformed(evt);
            }
            else if (evt.getSource() == jComboBox2) {
                panelPerjalanan.this.jComboBox2ActionPerformed(evt);
            }
            else if (evt.getSource() == newButton2) {
                panelPerjalanan.this.newButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == newButton3) {
                panelPerjalanan.this.newButton3ActionPerformed(evt);
            }
            else if (evt.getSource() == newButton4) {
                panelPerjalanan.this.newButton4ActionPerformed(evt);
            }
            else if (evt.getSource() == newButton6) {
                panelPerjalanan.this.newButton6ActionPerformed(evt);
            }
            else if (evt.getSource() == newButton5) {
                panelPerjalanan.this.newButton5ActionPerformed(evt);
            }
            else if (evt.getSource() == gantiLaporanButton) {
                panelPerjalanan.this.gantiLaporanButtonActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                panelPerjalanan.this.jButton2ActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    
    private void deleteDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDetailButtonActionPerformed
        int index = masterTable.getSelectedRow();
        app.table.Trips t = list.get(masterTable.convertRowIndexToModel(index));
        Collection<app.table.Perjalanan> ps = t.getPerjalananList();
        int[] selected = detailTable.getSelectedRows();
        List<app.table.Perjalanan> toRemove = new ArrayList<app.table.Perjalanan>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            selected[idx] = detailTable.convertRowIndexToModel(selected[idx]);
            int count = 0;
            Iterator<app.table.Perjalanan> iter = ps.iterator();
            while (count++ < selected[idx]) {
                iter.next();
            }
            app.table.Perjalanan p = iter.next();
            toRemove.add(p);
            entityManager.remove(p);
        }
        ps.removeAll(toRemove);
        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
    }//GEN-LAST:event_deleteDetailButtonActionPerformed

    private void newDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDetailButtonActionPerformed
        int index = masterTable.getSelectedRow();
        app.table.Trips t = list.get(masterTable.convertRowIndexToModel(index));
        Collection<app.table.Perjalanan> ps = t.getPerjalananList();
        if (ps == null) {
            ps = new LinkedList<app.table.Perjalanan>();
            t.setPerjalananList((List) ps);
        }
        app.table.Perjalanan p = new app.table.Perjalanan();
        Saldo ts  = new Saldo();
        Saldo ts1 = new Saldo();
        if (evt.getSource() == newButton2) {
                p = (Perjalanan) this.inputPanel2.getTarget();
                ts.setBankId((Bank) this.jComboBox2.getSelectedItem());
//                Pengeluaran p1 = new app.table.Pengeluaran();
                app.table.Transfer p1 = new app.table.Transfer();
                p1.setJumlah(p.getJumlah());
                p1.setKeterangan(p.getKeterangan());
                p1.setTanggal(p.getTanggal());
                ts1.setBankId(Peter);
                p.setTransaksi(ts1);                
                p1.setTransaksi(ts);
                p.setTransfer(p1);
                boolean simpan = utilsPanel.simpan(entityManager, p1);
                        if (simpan) {
                            utilsPanel.simpan(entityManager, p);
                            ps.add(p);
                        }
            }
            else if (evt.getSource() == newButton3) {
                System.out.println("Kirim/Pengeluaran");
                p = (Perjalanan) this.inputPanel3.getTarget();
                ts.setBankId((Bank) this.jComboBox3.getSelectedItem());
                Pemasukan p1 = new Pemasukan();
                p1.setTipe("CLOSE");
                p1.setJumlah(p.getJumlah());
                p1.setKeterangan(p.getKeterangan());
                p1.setTanggal(p.getTanggal());
                ts1.setBankId(Peter);
                p1.setTransaksi(ts);
                p.setTransaksi(ts1);
                p.setKembali(p1);
//                entityManager.persist(p1);
                boolean simpan = utilsPanel.simpan(entityManager, p);
                    if (simpan) {  ps.add(p); }   
            }
            else if (evt.getSource() == newButton4) {
                System.out.println("Pakai");
                p = (Perjalanan) this.inputPanel4.getTarget();
                ts.setBankId(Peter);
                p.setTransaksi(ts);
                boolean simpan = utilsPanel.simpan(entityManager, p);
                    if (simpan) {  ps.add(p); }   
            }
            else if (evt.getSource() == newButton5) {
                System.out.println("Belanja Mobil");
                KeuanganMobil A = (KeuanganMobil) this.inputPanel5.getTarget();
                ts.setBankId(Peter);
                A.setTransaksi(ts);
                A.setMobils((Mobil) jComboBox5.getSelectedItem());
                A.setTripsTripsId(t);
                A.setKeterangan(A.getKeterangan()+ A.getJenis());
//                System.out.println(A.getTransaksi().getBankId() == null);
                boolean simpan = utilsPanel.simpan(entityManager, A);
//                    if (simpan) {  ps.add(); }   
            }
//        p.setTransaksi(ts);
        p.setTripsTripsId(t);
//        entityManager.persist(p);
//        boolean simpan = false;
//            simpan =
        masterTable.clearSelection();
        masterTable.setRowSelectionInterval(index, index);
        int row = ps.size() - 1;
//        detailTable.setRowSelectionInterval(row, row);
//        detailTable.scrollRectToVisible(detailTable.getCellRect(row, 0, true));
        saveButtonActionPerformed(evt);
    }//GEN-LAST:event_newDetailButtonActionPerformed
    
    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        try {
        ((app.view.FixPanel.PanelBank)ShowRoom.jPanel5).Reset();            
        } catch (Exception e) {
        }
        bankList.clear();
        bankList.addAll(bankQuery.getResultList());
        mobilList.clear();
        mobilList.addAll(mobilQuery.getResultList());
        Peter = this.entityManager.find(app.table.Bank.class, -2);
        bankList.remove(Peter);
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
        Hitung();

    }//GEN-LAST:event_refreshButtonActionPerformed

    public void ResetPerjalan()
    {
        System.out.println("app.view.panel.perjalanan.panelPerjalanan.ResetPerjalan()");
        try {
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        bankList.clear();
        bankList.addAll(bankQuery.getResultList());
        mobilList.clear();
        mobilList.addAll(mobilQuery.getResultList());            
        } catch (Exception e) {
        }
    
    }
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<app.table.Trips> toRemove = new ArrayList<app.table.Trips>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            app.table.Trips t = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(t);
            entityManager.remove(t);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        app.table.Trips t = (app.table.Trips) this.inputPanel1.getTarget();
        entityManager.persist(t);
        list.add(t);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
        this.jDialog1.hide();
    }//GEN-LAST:event_newButtonActionPerformed
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
//                        try {
//            ((app.view.FixPanel.PanelBank)ShowRoom.jPanel5).Reset();        
//            } catch (Exception e) {
//            }
//                bankList.clear();
//                bankList.addAll(bankQuery.getResultList());

            refreshButtonActionPerformed(evt);
//            Util.RefreshLaporan();

        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<app.table.Trips> merged = new ArrayList<app.table.Trips>(list.size());
            for (app.table.Trips t : list) {
                merged.add(entityManager.merge(t));
            }
            list.clear();
            list.addAll(merged);
        }
//        this.refreshButton1ActionPerformed(evt);
        this.Hitung();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void newDetailButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDetailButton1ActionPerformed
        this.jDialog2.setSize(500, 400);
        this.jDialog2.setLocationRelativeTo(null);
        this.jDialog2.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_newDetailButton1ActionPerformed

    private void newDetailButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDetailButton2ActionPerformed
        // TODO add your handling code here:
        this.jDialog3.setSize(500, 400);
        this.jDialog3.setLocationRelativeTo(null);
        this.jDialog3.show();

    }//GEN-LAST:event_newDetailButton2ActionPerformed

    private void newDetailButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDetailButton3ActionPerformed
        // TODO add your handling code here:
        this.jDialog4.setSize(500, 400);
        this.jDialog4.setLocationRelativeTo(null);
        this.jDialog4.show();

    }//GEN-LAST:event_newDetailButton3ActionPerformed

    private void newButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButton1ActionPerformed
        this.jDialog1.setSize(500, 400);
        this.jDialog1.setLocationRelativeTo(null);
        this.jDialog1.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_newButton1ActionPerformed

    private void newButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButton2ActionPerformed
        this.newDetailButtonActionPerformed(evt);
        jDialog2.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_newButton2ActionPerformed

    private void newButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButton3ActionPerformed
        this.newDetailButtonActionPerformed(evt);
        jDialog3.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_newButton3ActionPerformed

    private void newButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButton4ActionPerformed
        this.newDetailButtonActionPerformed(evt);
        jDialog4.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_newButton4ActionPerformed

    private void refreshButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton1ActionPerformed
        // TODO add your handling code here:
        this.refreshButtonActionPerformed(evt);
    }//GEN-LAST:event_refreshButton1ActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        // TODO add your handling code here:
        this.saveButtonActionPerformed(evt);
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void newDetailButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDetailButton4ActionPerformed
        this.jDialog5.setSize(500, 400);
        this.jDialog5.setLocationRelativeTo(null);
        this.jDialog5.show();        // TODO add your handling code here:
    }//GEN-LAST:event_newDetailButton4ActionPerformed

    private void newButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButton5ActionPerformed
        this.newDetailButtonActionPerformed(evt);
        jDialog5.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_newButton5ActionPerformed

    private void newButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButton6ActionPerformed
        String cari = "%";
        cari += this.jTextField1.getText();
        cari += "%"; 
        TypedQuery<Mobil> createQuery = entityManager.createQuery(" SELECT b from Mobil b WHERE "
                + "b.noPolisiAktif LIKE :cari1 "+
                 " OR b.noPolisiLama LIKE :cari1",Mobil.class)
            .setParameter("cari1", cari);
        mobilList.clear();
        mobilList.addAll(createQuery.getResultList());        // TODO add your handling code here:
    }//GEN-LAST:event_newButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser=new JFileChooser(".");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel files","xls","excel");
        chooser.addChoosableFileFilter(filter);
        chooser.setFileFilter(filter);
        chooser.setFileSelectionMode(chooser.FILES_AND_DIRECTORIES);
        chooser.setDialogTitle("Save File");
        File filetemp = new File( System.getProperties().getProperty("user.home"),
            "Data Laporan Perjalanan "+new Date().toString().replace(":", "-")+".xls");
        chooser.setSelectedFile(filetemp);
        int reply = chooser.showSaveDialog(this);
        while ( chooser.getSelectedFile().exists()) {
            JOptionPane.showMessageDialog(this,"File telah ada\nGanti Nama");
            reply = chooser.showSaveDialog(this);
        }
        System.out.println("reply = " + reply);
        if (reply == 1 ) {
            return;
        }
        File file1 = chooser.getSelectedFile();
        File f = new File(file1.getParentFile(), "Data");
        f.mkdirs();
        SimpleDateFormat formator = new SimpleDateFormat("dd/MM/yyyy");
        DecimalFormat IDR = new DecimalFormat("###0");
        List a = list;
        File T = new File(f, "Daftar Pinjaman.CSV");
        List<File> cvs = new java.util.LinkedList<>();
        cvs.add(T);
        WriteStep data = CSVUtil.of(T)
            .type(app.table.Perjalanan.class)
            .properties(
                Tuple.of("Ref","tripsId", d -> d==null?" ":d),
                Tuple.of("keterangan","keterangan", d -> d==null?" ":d),
                Tuple.of("perjalananke","perjalananke", d -> d==null?" ":d),
                Tuple.of("tanggalBerangkat","tanggalBerangkat", d -> d==null?" ":formator.format(d)),
                Tuple.of("tanggalKembali","tanggalKembali", d -> d==null?" ":formator.format(d)),
                Tuple.of("totalKembali", "totalKembali", d -> d==null?"0":IDR.format(d) ),
                Tuple.of("totalKirim","totalKirim", d -> d==null?" ":IDR.format(d)),
                Tuple.of("totalPakai","totalPakai", d -> d==null?" ":IDR.format(d)),
                Tuple.of("totalSaldo","totalSaldo", d -> d==null?" ":IDR.format(d))
        ).dataList(a);
        try {
            data.write();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null
                , "Gagal Print, Karena file sementara terbuka\n"+e);
        }
        for (Trips peg : list) {
            String pe = peg.getTripsId()+"- KE "+
                        peg.getPerjalananke()+ " Berangkat" +
                        peg.getTanggalBerangkat().toString().replace(":", "-") +
                        ".CSV";
            File p = new File(f, pe);
            cvs.add(p);
//            List b = peg.getPerjalananList();
            PerjalananPemasukan pemasukan = new PerjalananPemasukan();
            PerjalananPengeluaran pengeluaran = new PerjalananPengeluaran();
            List b = app.table.Util.hitungSaldo(peg.getPerjalananList(), pemasukan,pengeluaran);
            b.add(pemasukan);
            b.add(pengeluaran);
            WriteStep dataList = CSVUtil.of(p)
            .type(app.table.Perjalanan.class)
            .properties(
                    Tuple.of("Ref", "id", null),
                    Tuple.of("Tanggal", "tanggal", d -> formator.format(d)),
                    Tuple.of("Keterangan", "keterangan", d -> d),
                    Tuple.of("Kirim", "kirim2", d -> d==null?"0":IDR.format(d) ),
                    Tuple.of("Kembalikan", "kembali2", d -> d==null?"0":IDR.format(d) ),
                    Tuple.of("Pakai", "pengeluaran", d -> d==null?"0":IDR.format(d) ),
                    Tuple.of("Saldo", "saldo", d -> IDR.format(d) )
            ).dataList(b);
            dataList.write();
        }
        try {
            ExcelConverter(cvs, file1);
            javax.swing.JOptionPane.showMessageDialog(null
                , "Berhasil Print");
            Desktop.getDesktop().open(file1);
            refreshButtonActionPerformed(evt);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null
                , "Gagal Print, Karena file sementara terbuka\n"+e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gantiLaporanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gantiLaporanButtonActionPerformed
        this.GantiDialog6.setSize(500, 400);
        this.GantiDialog6.setLocationRelativeTo(null);
        this.GantiDialog6.show();        // TODO add your handling code here:
    }//GEN-LAST:event_gantiLaporanButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = masterTable.getSelectedRow();
        app.table.Trips t = list.get(masterTable.convertRowIndexToModel(index));
        List<app.table.Perjalanan> ps = t.getPerjalananList();
        int[] selected = detailTable.getSelectedRows();
        for (int idx = 0; idx < selected.length; idx++) {
            selected[idx] = detailTable.convertRowIndexToModel(selected[idx]);
            int count = 0;
            Iterator<app.table.Perjalanan> iter = ps.iterator();
            while (count++ < selected[idx]) {
                iter.next();
            }
            app.table.Perjalanan p = iter.next();
            System.out.println("p = " + p);
            System.out.println("p = " + p.getTripsTripsId());

            Trips selectedItem = (Trips) jComboBox6.getSelectedItem();
            System.out.println("selectedItem = " + selectedItem);

            p.setTripsTripsId(selectedItem);
            System.out.println("p = " + p);
            System.out.println("p = " + p.getTripsTripsId());
            entityManager.merge(p.getTripsTripsId());
        }
        saveButtonActionPerformed(evt);
        refreshButtonActionPerformed(evt);
        GantiDialog6.hide();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog GantiDialog6;
    private java.util.List<app.table.Bank> bankList;
    private javax.persistence.Query bankQuery;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteDetailButton;
    private javax.swing.JScrollPane detailScrollPane;
    private javax.swing.JTable detailTable;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton gantiLaporanButton;
    private app.utils.inputPanel inputPanel1;
    private app.utils.inputPanel inputPanel2;
    private app.utils.inputPanel inputPanel3;
    private app.utils.inputPanel inputPanel4;
    private app.utils.inputPanel inputPanel5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private java.util.List<app.table.Trips> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private java.util.List<app.table.Mobil> mobilList;
    private javax.persistence.Query mobilQuery;
    private javax.swing.JButton newButton;
    private javax.swing.JButton newButton1;
    private javax.swing.JButton newButton2;
    private javax.swing.JButton newButton3;
    private javax.swing.JButton newButton4;
    private javax.swing.JButton newButton5;
    private javax.swing.JButton newButton6;
    private javax.swing.JButton newDetailButton;
    private javax.swing.JButton newDetailButton1;
    private javax.swing.JButton newDetailButton2;
    private javax.swing.JButton newDetailButton3;
    private javax.swing.JButton newDetailButton4;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton refreshButton1;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveButton1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelPerjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelPerjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelPerjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelPerjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new panelPerjalanan());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
    
    private void Hitung() {
    for (Trips trips : list) {
            List<Perjalanan> mop = trips.getPerjalananList();
            java.math.BigInteger saldo = new java.math.BigInteger("0");            
            java.math.BigInteger kirim = new java.math.BigInteger("0");            
            java.math.BigInteger pakai = new java.math.BigInteger("0");            
            for (Perjalanan a : mop) {
                kirim = kirim.add( a.getTransfer() == null ? BigInteger.ZERO: a.getTransfer().getJumlah());
                saldo = saldo.subtract(a.getPengeluaran());
                pakai = pakai.add(a.getPengeluaran());
                saldo = saldo.add(a.getPemasukan());
                a.setSaldo(saldo);
            }
            trips.setTotalSaldo(saldo);
            trips.setTotalPakai(pakai);
            trips.setTotalKirim(kirim);
        }
//    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Bank getPeter() {
        return Peter;
    }

    public void setPeter(Bank Peter) {
        this.Peter = Peter;
    }
    
}
