/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.panel.mobil;

import app.table.Bpkb;
import app.table.Debitur;
import app.table.KeuanganMobil;
import app.table.Mobil;
import com.toedter.calendar.JDateChooserCellEditor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javafx.collections.FXCollections;
import static javafx.collections.FXCollections.observableList;
import javafx.collections.ObservableList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author SEED
 */
public class panelMobil extends javax.swing.JPanel {

    /**
     * Creates new form Mobil
     */
    public panelMobil() {
        
        initComponents();
        this.mobilList
                .stream()
                .filter(a-> !a.getStatusMobil().contains("CLOSE"))
                .forEach((Mobil a) -> {
                    this.jTabbedPane1.add(new app.view.panel.mobil.subPanelMobil(),
                            a.getMobilId()+";"+
                            a.getMerk()+";"+
                            a.getType()+";"+
                            a.getTahun()+";"
                                    );                
                }
                
                );
        for (int i = 0; i < this.jTable1.getColumnCount(); i++) {
                this.jTable1.getColumnModel().getColumn(i).setPreferredWidth(250);
        }
        for (int i = 0; i < this.jTable2.getColumnCount(); i++) {
                this.jTable1.getColumnModel().getColumn(i).setPreferredWidth(250);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        blessingPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("blessingPU").createEntityManager();
        mobilQuery = java.beans.Beans.isDesignTime() ? null : blessingPUEntityManager.createQuery("SELECT m FROM Mobil m");
        mobilList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(mobilQuery.getResultList());
        debiturQuery1 = java.beans.Beans.isDesignTime() ? null : blessingPUEntityManager.createQuery("SELECT d FROM Debitur d");
        debiturList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(debiturQuery1.getResultList());
        bpkbQuery1 = java.beans.Beans.isDesignTime() ? null : blessingPUEntityManager.createQuery("SELECT b FROM Bpkb b");
        bpkbList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(bpkbQuery1.getResultList());
        jDialog1 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jYearChooser2 = new com.toedter.calendar.JYearChooser();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField15 = new javax.swing.JTextField();
        jDialog2 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jFileChooser3 = new javax.swing.JFileChooser();
        jFileChooser4 = new javax.swing.JFileChooser();
        jFileChooser5 = new javax.swing.JFileChooser();
        jFileChooser6 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BPKB = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jDialog1.setTitle("Mobil Baru");
        jDialog1.setSize(new java.awt.Dimension(800, 6));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA MOBIL"));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setPreferredSize(new java.awt.Dimension(400, 713));

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/view/panel/mobil/1.PNG"))); // NOI18N
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tampilan Depan"));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new java.awt.GridBagConstraints());

        jTextField7.setText("jTextField7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jTextField7, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/view/panel/mobil/1.PNG"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tampilan Samping Kiri"));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jLabel5, gridBagConstraints);

        jTextField13.setText("jTextField7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jTextField13, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/view/panel/mobil/1.PNG"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tampilan Samping Kanan"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel4.add(jLabel4, gridBagConstraints);

        jTextField14.setText("jTextField7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jTextField14, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/view/panel/mobil/1.PNG"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tampilan Belakang"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel4.add(jLabel3, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/view/panel/mobil/1.PNG"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Interior II"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        jPanel4.add(jLabel1, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/view/panel/mobil/1.PNG"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Interior I"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel4.add(jLabel2, gridBagConstraints);

        jTextField16.setText("jTextField7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jTextField16, gridBagConstraints);

        jTextField17.setText("jTextField7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jTextField17, gridBagConstraints);

        jTextField18.setText("jTextField7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jTextField18, gridBagConstraints);

        jScrollPane4.setViewportView(jPanel4);

        jPanel6.add(jScrollPane4, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 10, 10));

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jLabel20.setText("NOMOR POLISI AKTIF");
        jPanel2.add(jLabel20);

        jLabel7.setText("PEMILIK SEBELUMNYA");
        jPanel2.add(jLabel7);

        jLabel21.setText("NOMOR BPKB");
        jPanel2.add(jLabel21);

        jLabel36.setText("TANGGAL TERIMA BPKB");
        jPanel2.add(jLabel36);

        jLabel22.setText("MERK");
        jPanel2.add(jLabel22);

        jLabel23.setText("TYPE");
        jPanel2.add(jLabel23);

        jLabel24.setText("JENIS");
        jPanel2.add(jLabel24);

        jLabel25.setText("TAHUN");
        jPanel2.add(jLabel25);

        jLabel26.setText("CC SILINDER");
        jPanel2.add(jLabel26);

        jLabel31.setText("WARNA");
        jPanel2.add(jLabel31);

        jLabel27.setText("NO RANGKA");
        jPanel2.add(jLabel27);

        jLabel28.setText("NO MESIN");
        jPanel2.add(jLabel28);

        jLabel29.setText("BAHAN BAKAR");
        jPanel2.add(jLabel29);

        jLabel32.setText("PENJUAL");
        jPanel2.add(jLabel32);

        jLabel33.setText("HARGA PEMBELIAN");
        jPanel2.add(jLabel33);

        jLabel35.setText("DP PERTAMA");
        jPanel2.add(jLabel35);

        jLabel34.setText("TANGGAL PEMBELIAN");
        jPanel2.add(jLabel34);

        jLabel30.setText("KETERANGAN");
        jPanel2.add(jLabel30);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 10, 10));

        jButton2.setText("RESET");
        jPanel3.add(jButton2);

        jTextField1.setText("nopol");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);

        jTextField6.setText("PEMILIK SEBELU");
        jPanel3.add(jTextField6);

        jTextField2.setText("bpkb");
        jPanel3.add(jTextField2);

        jDateChooser1.setDate(new java.util.Date());
        jPanel3.add(jDateChooser1);

        jTextField3.setText("merk");
        jPanel3.add(jTextField3);

        jTextField4.setText("tipe");
        jPanel3.add(jTextField4);

        jTextField5.setText("jenis");
        jPanel3.add(jTextField5);
        jPanel3.add(jYearChooser1);

        jYearChooser2.setYear(500);
        jPanel3.add(jYearChooser2);

        jTextField8.setText("warna");
        jPanel3.add(jTextField8);

        jTextField9.setText("rangka");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField9);

        jTextField10.setText("mesin");
        jPanel3.add(jTextField10);

        jTextField11.setText("bahan baka");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField11);

        jTextField12.setText("penjueal");
        jPanel3.add(jTextField12);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField1.setValue( 0l);
        jPanel3.add(jFormattedTextField1);

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField2.setValue(0l);
        jPanel3.add(jFormattedTextField2);

        jDateChooser2.setDate(new java.util.Date());
        jPanel3.add(jDateChooser2);

        jTextField15.setText("tetsa eatea");
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField15);

        jPanel1.add(jPanel3);

        jPanel6.add(jPanel1, java.awt.BorderLayout.CENTER);

        jDialog1.getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setApproveButtonText("Open");
        jFileChooser1.setApproveButtonToolTipText("");
        jFileChooser1.setDialogTitle("SCAN KTP");
        jFileChooser1.setFileFilter(new FileNameExtensionFilter(
            "Image files(jpg,png,bmp)", ImageIO.getReaderFileSuffixes()));
    jFileChooser1.setDragEnabled(true);
    jFileChooser1.setRequestFocusEnabled(false);
    jFileChooser1.setSelectedFiles(null);
    jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jFileChooser1ActionPerformed(evt);
        }
    });

    jFileChooser2.setAcceptAllFileFilterUsed(false);
    jFileChooser2.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
    jFileChooser2.setApproveButtonText("Open");
    jFileChooser2.setApproveButtonToolTipText("");
    jFileChooser2.setDialogTitle("SCAN KTP");
    jFileChooser2.setFileFilter(new FileNameExtensionFilter(
        "Image files(jpg,png,bmp)", ImageIO.getReaderFileSuffixes()));
jFileChooser2.setDragEnabled(true);
jFileChooser2.setRequestFocusEnabled(false);
jFileChooser2.setSelectedFiles(null);
jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jFileChooser2ActionPerformed(evt);
    }
    });

    jFileChooser3.setAcceptAllFileFilterUsed(false);
    jFileChooser3.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
    jFileChooser3.setApproveButtonText("Open");
    jFileChooser3.setApproveButtonToolTipText("");
    jFileChooser3.setDialogTitle("SCAN KTP");
    jFileChooser3.setFileFilter(new FileNameExtensionFilter(
        "Image files(jpg,png,bmp)", ImageIO.getReaderFileSuffixes()));
jFileChooser3.setDragEnabled(true);
jFileChooser3.setRequestFocusEnabled(false);
jFileChooser3.setSelectedFiles(null);
jFileChooser3.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jFileChooser3ActionPerformed(evt);
    }
    });

    jFileChooser4.setAcceptAllFileFilterUsed(false);
    jFileChooser4.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
    jFileChooser4.setApproveButtonText("Open");
    jFileChooser4.setApproveButtonToolTipText("");
    jFileChooser4.setDialogTitle("SCAN KTP");
    jFileChooser4.setFileFilter(new FileNameExtensionFilter(
        "Image files(jpg,png,bmp)", ImageIO.getReaderFileSuffixes()));
jFileChooser4.setDragEnabled(true);
jFileChooser4.setRequestFocusEnabled(false);
jFileChooser4.setSelectedFiles(null);
jFileChooser4.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jFileChooser4ActionPerformed(evt);
    }
    });

    jFileChooser5.setAcceptAllFileFilterUsed(false);
    jFileChooser5.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
    jFileChooser5.setApproveButtonText("Open");
    jFileChooser5.setApproveButtonToolTipText("");
    jFileChooser5.setDialogTitle("SCAN KTP");
    jFileChooser5.setFileFilter(new FileNameExtensionFilter(
        "Image files(jpg,png,bmp)", ImageIO.getReaderFileSuffixes()));
jFileChooser5.setDragEnabled(true);
jFileChooser5.setRequestFocusEnabled(false);
jFileChooser5.setSelectedFiles(null);
jFileChooser5.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jFileChooser5ActionPerformed(evt);
    }
    });

    jFileChooser6.setAcceptAllFileFilterUsed(false);
    jFileChooser6.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
    jFileChooser6.setApproveButtonText("Open");
    jFileChooser6.setApproveButtonToolTipText("");
    jFileChooser6.setDialogTitle("SCAN KTP");
    jFileChooser6.setFileFilter(new FileNameExtensionFilter(
        "Image files(jpg,png,bmp)", ImageIO.getReaderFileSuffixes()));
jFileChooser6.setDragEnabled(true);
jFileChooser6.setRequestFocusEnabled(false);
jFileChooser6.setSelectedFiles(null);
jFileChooser6.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jFileChooser6ActionPerformed(evt);
    }
    });

    setLayout(new java.awt.BorderLayout());

    jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

    jPanel5.setLayout(new java.awt.BorderLayout());

    jButton3.setText("TAMBAH");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel7.add(jButton3);

    jButton4.setText("SIMPAN");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });
    jPanel7.add(jButton4);

    jButton6.setText("HAPUS");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });
    jPanel7.add(jButton6);

    jPanel5.add(jPanel7, java.awt.BorderLayout.NORTH);

    jTable1.setDefaultEditor(Date.class, new JDateChooserCellEditor());
    jTable1.setDefaultRenderer(long.class, new app.utils.CurrencyTableCellRenderer());
    jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    jTable1.setRowHeight(24);

    org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${mobilList}");
    org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
    org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mobilId}"));
    columnBinding.setColumnName("Ref");
    columnBinding.setColumnClass(Integer.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${noPolisiAktif}"));
    columnBinding.setColumnName("No Polisi Aktif");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${noPolisiLama}"));
    columnBinding.setColumnName("No Polisi Lama");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pemilikBaru}"));
    columnBinding.setColumnName("Pemilik Baru");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pemilikLama}"));
    columnBinding.setColumnName("Pemilik Lama");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${merk}"));
    columnBinding.setColumnName("Merk");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${type}"));
    columnBinding.setColumnName("Type");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${jenis}"));
    columnBinding.setColumnName("Jenis");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tahun}"));
    columnBinding.setColumnName("Tahun");
    columnBinding.setColumnClass(Integer.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${warna}"));
    columnBinding.setColumnName("Warna");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${silinder}"));
    columnBinding.setColumnName("Silinder");
    columnBinding.setColumnClass(Integer.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${noRangka}"));
    columnBinding.setColumnName("No Rangka");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${noMesin}"));
    columnBinding.setColumnName("No Mesin");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bahanBakar}"));
    columnBinding.setColumnName("Bahan Bakar");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bpkb.noBpkb}"));
    columnBinding.setColumnName("Bpkb");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${debitur.nama}"));
    columnBinding.setColumnName("Debitur");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${keterangan}"));
    columnBinding.setColumnName("Keterangan");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hargaPembelian}"));
    columnBinding.setColumnName("Harga Beli");
    columnBinding.setColumnClass(Long.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tanggalBeli}"));
    columnBinding.setColumnName("Tanggal Beli");
    columnBinding.setColumnClass(java.util.Date.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${hargaJual}"));
    columnBinding.setColumnName("Harga Jual");
    columnBinding.setColumnClass(Long.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tanggalJual}"));
    columnBinding.setColumnName("Tanggal Jual");
    columnBinding.setColumnClass(java.util.Date.class);
    bindingGroup.addBinding(jTableBinding);
    jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${hapus}"), jTable1, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
    bindingGroup.addBinding(binding);

    jScrollPane1.setViewportView(jTable1);
    if (jTable1.getColumnModel().getColumnCount() > 0) {
        jTable1.getColumnModel().getColumn(15).setResizable(false);
    }

    jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jTabbedPane1.addTab("MOBIL", jPanel5);

    BPKB.setLayout(new java.awt.BorderLayout());

    jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

    jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    jTable2.setDefaultEditor(Date.class, new JDateChooserCellEditor());
    jTable2.setRowHeight(24);

    eLProperty = org.jdesktop.beansbinding.ELProperty.create("${bpkbList1}");
    jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable2);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bpkbId}"));
    columnBinding.setColumnName("Ref");
    columnBinding.setColumnClass(Integer.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${noBpkb}"));
    columnBinding.setColumnName("No Bpkb");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${anBpkb}"));
    columnBinding.setColumnName("An Bpkb");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tglTerima}"));
    columnBinding.setColumnName("Tgl Terima");
    columnBinding.setColumnClass(java.util.Date.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tglCb}"));
    columnBinding.setColumnName("Tgl Cb");
    columnBinding.setColumnClass(java.util.Date.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tglKembaliCb}"));
    columnBinding.setColumnName("Tgl Kembali Cb");
    columnBinding.setColumnClass(java.util.Date.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tglBbn}"));
    columnBinding.setColumnName("Tgl Bbn");
    columnBinding.setColumnClass(java.util.Date.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tglKembaliBbn}"));
    columnBinding.setColumnName("Tgl Kembali Bbn");
    columnBinding.setColumnClass(java.util.Date.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tglLeasing}"));
    columnBinding.setColumnName("Tgl Leasing");
    columnBinding.setColumnClass(java.util.Date.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${posisi}"));
    columnBinding.setColumnName("Posisi");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mobil.mobilId}"));
    columnBinding.setColumnName("Ref");
    columnBinding.setColumnClass(Integer.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mobil.noPolisiAktif}"));
    columnBinding.setColumnName("No Polisi Aktif");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ket}"));
    columnBinding.setColumnName("Ket");
    columnBinding.setColumnClass(String.class);
    bindingGroup.addBinding(jTableBinding);
    jTableBinding.bind();
    jScrollPane2.setViewportView(jTable2);

    BPKB.add(jScrollPane2, java.awt.BorderLayout.CENTER);

    jButton7.setText("SIMPAN");
    jPanel8.add(jButton7);

    jButton8.setText("LIHAT MOBIL");
    jPanel8.add(jButton8);

    BPKB.add(jPanel8, java.awt.BorderLayout.PAGE_START);

    jTabbedPane1.addTab("BPKB", BPKB);

    jPanel9.setLayout(new java.awt.BorderLayout());

    jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    jTable3.setRowHeight(24);

    eLProperty = org.jdesktop.beansbinding.ELProperty.create("${debiturList1}");
    jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable3);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${debiturId}"));
    columnBinding.setColumnName("Ref");
    columnBinding.setColumnClass(Integer.class);
    columnBinding.setEditable(false);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nama}"));
    columnBinding.setColumnName("Nama");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${alamat}"));
    columnBinding.setColumnName("Alamat");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${noHp}"));
    columnBinding.setColumnName("No Hp");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${noKtp}"));
    columnBinding.setColumnName("No Ktp");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${norek}"));
    columnBinding.setColumnName("Norek");
    columnBinding.setColumnClass(String.class);
    columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bank}"));
    columnBinding.setColumnName("Bank");
    columnBinding.setColumnClass(String.class);
    bindingGroup.addBinding(jTableBinding);
    jTableBinding.bind();
    jScrollPane3.setViewportView(jTable3);

    jPanel9.add(jScrollPane3, java.awt.BorderLayout.CENTER);

    jButton9.setText("SIMPAN");
    jPanel10.add(jButton9);

    jButton10.setText("LIHAT MOBIL");
    jPanel10.add(jButton10);

    jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_START);

    jTabbedPane1.addTab("DEBITUR", jPanel9);

    add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("app.view.panel.mobil.panelMobil.jButton1ActionPerformed()");
        //data baru
        Mobil baru = new Mobil();
        Bpkb bpkb = new Bpkb();
        Debitur debitur = new Debitur();
        List<KeuanganMobil> KM = new ArrayList<>();; 
        KeuanganMobil dp = new KeuanganMobil();
        //isi data baru
        baru.setNoPolisiAktif(this.jTextField1.getText());
        baru.setPemilikLama(this.jTextField6.getText());
        bpkb.setNoBpkb(this.jTextField2.getText());
        bpkb.setTglTerima(this.jDateChooser1.getDate());
        bpkb.setNoPolisiAktif(baru.getNoPolisiAktif());
        baru.setMerk(this.jTextField3.getText());
        baru.setType(this.jTextField4.getText());
        baru.setJenis(this.jTextField5.getText());
        baru.setTahun(this.jYearChooser1.getYear());
        baru.setSilinder(this.jYearChooser2.getYear());
        baru.setWarna(this.jTextField8.getText());
        baru.setNoRangka(this.jTextField9.getText());
        baru.setNoMesin(this.jTextField10.getText());
        baru.setBahanBakar(this.jTextField11.getText());        
        baru.setPenjual(this.jTextField12.getText());
        baru.setHargaPembelian((Integer) (int) (long) this.jFormattedTextField1.getValue());
        baru.setDpPertama((Integer) (int) (long) this.jFormattedTextField1.getValue());
        baru.setTanggalBeli(this.jDateChooser2.getDate());     
        baru.setKeterangan(this.jTextField15.getText());
        baru.setStatusMobil("OPEN");
        dp.setKredit((long) this.jFormattedTextField1.getValue());
        dp.setTanggal(baru.getTanggalBeli());
        dp.setKeterangan("Dp Pertama");
        //relasikan data
        KM.add(dp);
        baru.setBpkb(bpkb);
        baru.setDebitur(debitur);
        baru.setKeuanganMobils(KM);
        this.persist(baru);
        javax.swing.JOptionPane.showMessageDialog(this.getRootPane(), 
                (this.mobilList.add(baru)? "Berhasil":"Gagal" )
                        +"Menyimpan Mobil = \n"
                        +"NO = " + baru.getMobilId()
                        +"\nNO = " + baru.getMerk()
                        +"\nNO = " + baru.getType()
        );
        this.debiturList1.add(debitur);
        this.bpkbList1.add(bpkb);
        this.jTabbedPane1.add(new app.view.panel.mobil.subPanelMobil(),
                            baru.getMobilId()+";"+
                            baru.getMerk()+";"+
                            baru.getType()+";"+
                            baru.getTahun()+";"
                                    ); 
    }//GEN-LAST:event_jButton1ActionPerformed

    public List<Mobil> getMobilList() {
        return mobilList;
    }

    public void setMobilList(List<Mobil> mobilList) {
//        this.bindingGroup.unbind();
        this.mobilList = mobilList;
//        this.bindingGroup.bind();

    }

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.out.println("app.view.panel.mobil.panelMobil.jButton4ActionPerformed()");
        if (!this.blessingPUEntityManager.getTransaction().isActive()) 
                this.blessingPUEntityManager.getTransaction().begin();
        this.blessingPUEntityManager.getTransaction().commit();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jDialog1.setSize(800, 700);
        this.jDialog1.setLocationRelativeTo(null);
        this.jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.out.println("app.view.panel.mobil.panelMobil.jButton6ActionPerformed()");
        if (!this.blessingPUEntityManager.getTransaction().isActive()) 
                this.blessingPUEntityManager.getTransaction().begin();        
        this.blessingPUEntityManager.remove(this.getHapus());
        this.blessingPUEntityManager.getTransaction().commit();
        boolean remove = this.mobilList.remove(this.getHapus());
//        System.out.println(this.getHapus().getDebitur());
//        this.debiturList1.remove(this.getHapus().getDebitur());
//        this.bpkbList1.remove(this.getHapus().getBpkb());
        javax.swing.JOptionPane.showMessageDialog(this.getRootPane(), 
                (remove ? "Berhasil":"Gagal" )+" Menghapus\nNama Product = "+ this.jTextField1.getText()
        );        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    int returnVal = this.jFileChooser1.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        try {
            this.jTextField7.setText(this.jFileChooser1.getSelectedFile().getCanonicalPath());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked
    File gambar1;
    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        gambar1 = jFileChooser1.getSelectedFile();
        System.out.println("app.view.panel.mobil.panelMobil.jFileChooser1ActionPerformed()");
        System.out.println(evt.getActionCommand());
        System.out.println(evt.getID());
        System.out.println(evt.getSource());
            try {
                BufferedImage img = ImageIO.read(gambar1);
                ImageIcon ii = new javax.swing.ImageIcon(new ImageIcon
                                (gambar1.toString()).getImage().getScaledInstance(300, 140, Image.SCALE_DEFAULT));
                jLabel6.setIcon(ii);
            } catch (IOException ex) {
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed
    File gambar2,gambar3,gambar4,gambar5,gambar6;
    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
        gambar2 = jFileChooser1.getSelectedFile();
        System.out.println("app.view.panel.mobil.panelMobil.jFileChooser2ActionPerformed()");
        System.out.println(evt.getActionCommand());
        System.out.println(evt.getID());
        System.out.println(evt.getSource());
            try {
                BufferedImage img = ImageIO.read(gambar2);
                ImageIcon ii = new javax.swing.ImageIcon(new ImageIcon
                                (gambar2.toString()).getImage().getScaledInstance(300, 140, Image.SCALE_DEFAULT));
                jLabel5.setIcon(ii);
            } catch (IOException ex) {
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    int returnVal = this.jFileChooser2.showOpenDialog(this);
    
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        try {
            this.jTextField13.setText(this.jFileChooser1.getSelectedFile().getCanonicalPath());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jFileChooser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser3ActionPerformed

    private void jFileChooser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser4ActionPerformed

    private void jFileChooser5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser5ActionPerformed

    private void jFileChooser6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser6ActionPerformed

    public List<Bpkb> getBpkbList1() {
        return bpkbList1;
    }

    public void setBpkbList1(List<Bpkb> bpkbList1) {
        this.bindingGroup.unbind();
        this.bpkbList1 = bpkbList1;
        this.bindingGroup.bind();
    }

    public List<Debitur> getDebiturList1() {
        return debiturList1;
    }

    public void setDebiturList1(List<Debitur> debiturList1) {
        this.bindingGroup.bind();
        this.debiturList1 = debiturList1;
        this.bindingGroup.bind();
    }
//    private Mobil baru;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BPKB;
    private javax.persistence.EntityManager blessingPUEntityManager;
    private java.util.List<app.table.Bpkb> bpkbList1;
    private javax.persistence.Query bpkbQuery1;
    private java.util.List<app.table.Debitur> debiturList1;
    private javax.persistence.Query debiturQuery1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JFileChooser jFileChooser4;
    private javax.swing.JFileChooser jFileChooser5;
    private javax.swing.JFileChooser jFileChooser6;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JYearChooser jYearChooser2;
    private java.util.List<app.table.Mobil> mobilList;
    private javax.persistence.Query mobilQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    
    public void persist(Object object) {
        if (!this.blessingPUEntityManager.getTransaction().isActive())         
            blessingPUEntityManager.getTransaction().begin();
        try {
            blessingPUEntityManager.persist(object);
            blessingPUEntityManager.getTransaction().commit();
        } catch (Exception e) {
            e.printStackTrace();
            blessingPUEntityManager.getTransaction().rollback();
        } finally {
//            blessingPUEntityManager.close();
            System.out.println(object+"=persisted");
        }
    }
    private Mobil hapus = new Mobil();

    public Mobil getHapus() {
        return hapus;
    }

    public void setHapus(Mobil hapus) {
        this.hapus = hapus;
    }
    
}
