/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view.panel.mobil;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author SEED
 */
public class subPanelMobil extends javax.swing.JPanel {

    /**
     * Creates new form subPanelMobil
     */
    File gambar;
    public subPanelMobil() {
        initComponents();
        this.jFileChooser1.addActionListener((ActionEvent e) -> {
            System.out.println(jFileChooser1.getSelectedFile());
            
            gambar = jFileChooser1.getSelectedFile();
            try {
                BufferedImage img = ImageIO.read(gambar);
                ImageIcon ii = new javax.swing.ImageIcon(new ImageIcon
                                (gambar.toString()).getImage().getScaledInstance(400, 230, Image.SCALE_DEFAULT));
                jLabel40.setIcon(ii);
            } catch (IOException ex) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField41 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();

        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setApproveButtonText("Open");
        jFileChooser1.setApproveButtonToolTipText("");
        jFileChooser1.setDialogTitle("SCAN KTP");
        jFileChooser1.setFileFilter(new FileNameExtensionFilter(
            "Image files(jpg,png,bmp)", ImageIO.getReaderFileSuffixes()));
    jFileChooser1.setDragEnabled(true);
    jFileChooser1.setRequestFocusEnabled(false);
    jFileChooser1.setSelectedFiles(null);

    setLayout(new java.awt.GridBagLayout());

    jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Debitur", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

    jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA MOBIL"));
    jPanel8.setLayout(new java.awt.GridLayout(0, 2, 2, 2));

    jLabel2.setText("UNIT ID");
    jPanel8.add(jLabel2);

    jTextField13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField13ActionPerformed(evt);
        }
    });
    jPanel8.add(jTextField13);

    jLabel3.setText("NO BPKB ");
    jPanel8.add(jLabel3);
    jPanel8.add(jTextField14);

    jLabel4.setText("NO STNK LAMA");
    jPanel8.add(jLabel4);
    jPanel8.add(jTextField16);

    jLabel5.setText("NO STNK BARU");
    jPanel8.add(jLabel5);
    jPanel8.add(jTextField31);

    jLabel7.setText("NAMA PEMILIK LAMA");
    jPanel8.add(jLabel7);
    jPanel8.add(jTextField17);

    jLabel6.setText("NAMA PEMILIK BARU");
    jPanel8.add(jLabel6);
    jPanel8.add(jTextField18);

    jLabel9.setText("PENJUAL");
    jPanel8.add(jLabel9);
    jPanel8.add(jTextField19);

    jLabel18.setText("HARGA BELI");
    jPanel8.add(jLabel18);
    jPanel8.add(jTextField29);

    jLabel8.setText("TANGGAL BELI");
    jPanel8.add(jLabel8);
    jPanel8.add(jTextField20);

    jLabel10.setText("TANGGAL PELUNASAN PEMBELIAN");
    jPanel8.add(jLabel10);
    jPanel8.add(jTextField21);

    jLabel11.setText("DEBITUR");
    jPanel8.add(jLabel11);
    jPanel8.add(jTextField22);

    jLabel13.setText("HARGA JUAL");
    jPanel8.add(jLabel13);
    jPanel8.add(jTextField23);

    jLabel12.setText("TANGGAL JUAL");
    jPanel8.add(jLabel12);
    jPanel8.add(jTextField24);

    jLabel19.setText("TANGGAL PELUNASAN PENJUALAN");
    jPanel8.add(jLabel19);
    jPanel8.add(jTextField30);

    jLabel15.setText("TOTAL DEBIT");
    jPanel8.add(jLabel15);
    jPanel8.add(jTextField25);

    jLabel17.setText("TOTAL KREDIT");
    jPanel8.add(jLabel17);
    jPanel8.add(jTextField26);

    jLabel16.setText("REFUND");
    jPanel8.add(jLabel16);
    jPanel8.add(jTextField27);

    jLabel14.setText("TOTAL PROFIT");
    jPanel8.add(jLabel14);
    jPanel8.add(jTextField28);

    jLabel32.setText("STATUS");
    jPanel8.add(jLabel32);
    jPanel8.add(jTextField32);

    jTabbedPane1.addTab("DATA", jPanel8);

    jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "KEUANGAN MOBIL"));
    jPanel7.setLayout(new java.awt.GridBagLayout());

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "TANGGAL", "DEBIT", "KREDIT", "KET"
        }
    ));
    jScrollPane1.setViewportView(jTable1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    jPanel7.add(jScrollPane1, gridBagConstraints);

    jLabel33.setText("TOTAL KREDIT");
    jPanel7.add(jLabel33, new java.awt.GridBagConstraints());

    jLabel34.setText("TOTAL DEBIT");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    jPanel7.add(jLabel34, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel7.add(jTextField33, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel7.add(jTextField34, gridBagConstraints);

    jTabbedPane1.addTab("KEUANGAN", jPanel7);

    jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA MOBIL"));
    jPanel9.setLayout(new java.awt.GridBagLayout());

    jLabel35.setText("FOTO KTP");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    jPanel9.add(jLabel35, gridBagConstraints);

    jLabel36.setText("FILE GAMBAR KTP");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    jPanel9.add(jLabel36, gridBagConstraints);

    jTextField35.setMinimumSize(new java.awt.Dimension(400, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jTextField35, gridBagConstraints);

    jLabel37.setText("ALAMAT");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    jPanel9.add(jLabel37, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jTextField36, gridBagConstraints);

    jLabel38.setText("NOMOR HP");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    jPanel9.add(jLabel38, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jTextField37, gridBagConstraints);

    jLabel39.setText("NOMOR IDENTITAS");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    jPanel9.add(jLabel39, gridBagConstraints);

    jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/view/panel/mobil/1.PNG"))); // NOI18N
    jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel40MouseClicked(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.ipadx = 10;
    jPanel9.add(jLabel40, gridBagConstraints);

    jLabel41.setText("BANK");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    jPanel9.add(jLabel41, gridBagConstraints);

    jLabel42.setText("NOREK");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    jPanel9.add(jLabel42, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jTextField39, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jTextField40, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jTextField38, gridBagConstraints);

    jButton3.setText("SIMPAN");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jButton3, gridBagConstraints);

    jTextField41.setMinimumSize(new java.awt.Dimension(400, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jTextField41, gridBagConstraints);

    jLabel43.setText("NAMA");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    jPanel9.add(jLabel43, gridBagConstraints);

    jTabbedPane1.addTab("DEBITUR", jPanel9);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipadx = 114;
    gridBagConstraints.ipady = 49;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    add(jTabbedPane1, gridBagConstraints);

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true), "GAMBAR MOBIL"));
    jPanel5.setLayout(new java.awt.GridLayout(1, 0));
    jPanel5.add(jLabel1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipadx = 314;
    gridBagConstraints.ipady = 154;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    add(jPanel5, gridBagConstraints);

    jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA MOBIL"));
    jPanel6.setLayout(new java.awt.GridLayout(0, 2, 2, 3));

    jPanel2.setLayout(new java.awt.GridLayout(0, 1));

    jButton1.setText("HAPUS");
    jPanel2.add(jButton1);

    jLabel20.setText("NOMOR POLISI AKTIF");
    jPanel2.add(jLabel20);

    jLabel21.setText("NOMOR BPKB");
    jPanel2.add(jLabel21);

    jLabel22.setText("MERK");
    jPanel2.add(jLabel22);

    jLabel23.setText("TYPE");
    jPanel2.add(jLabel23);

    jLabel24.setText("JENIS");
    jPanel2.add(jLabel24);

    jLabel25.setText("TAHUN");
    jPanel2.add(jLabel25);

    jLabel26.setText("CC SILINDER");
    jPanel2.add(jLabel26);

    jLabel31.setText("WARNA");
    jPanel2.add(jLabel31);

    jLabel27.setText("NO RANGKA");
    jPanel2.add(jLabel27);

    jLabel28.setText("NO MESIN");
    jPanel2.add(jLabel28);

    jLabel29.setText("BAHAN BAKAR");
    jPanel2.add(jLabel29);

    jLabel30.setText("KETERANGAN");
    jPanel2.add(jLabel30);

    jPanel6.add(jPanel2);

    jPanel1.setLayout(new java.awt.GridLayout(0, 1));

    jButton2.setText("CLOSE");
    jPanel1.add(jButton2);

    jTextField1.setText("NOMOR POLISI");
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField1ActionPerformed(evt);
        }
    });
    jPanel1.add(jTextField1);

    jTextField2.setText("NOMOR BKPB");
    jPanel1.add(jTextField2);

    jTextField3.setText("MERK");
    jPanel1.add(jTextField3);

    jTextField4.setText("TYPE");
    jPanel1.add(jTextField4);

    jTextField5.setText("JENIS");
    jPanel1.add(jTextField5);

    jTextField6.setText("TAHUN");
    jPanel1.add(jTextField6);

    jTextField7.setText("OC SILINDER");
    jPanel1.add(jTextField7);

    jTextField8.setText("WARNA");
    jPanel1.add(jTextField8);

    jTextField9.setText("NO RANGKA");
    jPanel1.add(jTextField9);

    jTextField10.setText("NO MESIN");
    jPanel1.add(jTextField10);

    jTextField11.setText("BAHAN BAKAR");
    jTextField11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField11ActionPerformed(evt);
        }
    });
    jPanel1.add(jTextField11);

    jTextField12.setText("KETERANGAN");
    jPanel1.add(jTextField12);

    jPanel6.add(jPanel1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipadx = 98;
    gridBagConstraints.ipady = 19;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    add(jPanel6, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
    int returnVal = this.jFileChooser1.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        try {
            this.jTextField35.setText(this.jFileChooser1.getSelectedFile().getCanonicalPath());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel40MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
